services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ./api-gateway/public:/app/public
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
      - NOTIFICATION_SERVICE_URL=http://notification-service:8083
      - TRANSACTION_SERVICE_URL=http://transaction-service:8084
    depends_on:
      - product-service
      - order-service
      - notification-service
      - transaction-service
    networks:
      - microservices-network

  product-service:
    build:
      context: ./product-service
    ports:
      - "9091:8081"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - microservices-network

  order-service:
    build:
      context: ./order-service
    ports:
      - "8092:8082"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8083
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - product-service
      - notification-service
    networks:
      - microservices-network

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "9093:8083"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - microservices-network

  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "9094:8084"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
